export const ADDING_RESTAURANT = 'ADDING_RESTAURANT';
export const ADD_RESTAURANT_SUCCESS = 'ADD_RESTAURANT_SUCCESS';
export const ADD_RESTAURANT_FAILED = 'ADD_RESTAURANT_FAILED';
export const GETTING_RESTAURANTS = 'GETTING_RESTAURANTS';
export const GET_RESTAURANTS_SUCCESS = 'GET_RESTAURANTS_SUCCESS';
export const GET_RESTAURANTS_FAILURE = 'GET_RESTAURANTS_FAILURE';
export const AUTHENTICATING = 'AUTHENTICATING';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTEHTICATION_FAILURE = 'AUTHENTICATION_FAILURE';
export const ERROR_FLAG_ON = 'ERROR_FLAG_ON';
export const ERROR_FLAG_OFF = 'ERROR_FLAG_OFF';

